# Generated by Django 5.0.6 on 2024-06-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_id_proof_caters_registration_id_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restauarant_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=25, null=True)),
                ('restaurant_name', models.CharField(max_length=25, null=True)),
                ('location', models.CharField(max_length=25, null=True)),
                ('map_link', models.CharField(max_length=250, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('restaurant_license', models.FileField(null=True, upload_to='')),
                ('id_proof', models.FileField(null=True, upload_to='')),
                ('r_image', models.ImageField(null=True, upload_to='')),
                ('rk_image', models.ImageField(null=True, upload_to='')),
                ('approved', models.BooleanField(default=False)),
                ('login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Restuarant_registration',
        ),
    ]
