# Generated by Django 5.0.6 on 2024-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_food_restaurants_admin_accept_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_food_restaurants',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
