# Generated by Django 5.0.6 on 2024-06-30 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_food_restaurants_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_restaurent_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(null=True)),
                ('booked_date', models.DateTimeField(null=True)),
                ('restaurant_food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_food_restaurants')),
            ],
        ),
    ]
