# Generated by Django 5.0.6 on 2024-06-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_restaurent_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_restaurent_food',
            new_name='Booking_restaurant_food',
        ),
    ]
