# Generated by Django 5.0.6 on 2024-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_booking_restaurent_food_booking_restaurant_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_food_restaurants',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
