# Generated by Django 5.0.6 on 2024-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_add_food_restaurants_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_food_caters',
            name='admin_accept_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='add_food_caters',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='add_food_caters',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
