# Generated by Django 5.0.6 on 2024-06-30 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_add_food_caters_admin_accept_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_restaurant_food',
            name='restaurant_food_id',
        ),
        migrations.AddField(
            model_name='booking_restaurant_food',
            name='caters_food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_food_caters'),
        ),
    ]
