# Generated by Django 5.0.6 on 2024-06-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_booking_restaurant_food_restaurant_food_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_restaurant_food',
            name='caters_food_id',
        ),
        migrations.AddField(
            model_name='booking_restaurant_food',
            name='restaurant_food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_food_restaurants'),
        ),
        migrations.CreateModel(
            name='Booking_caters_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(null=True)),
                ('booked_date', models.DateTimeField(null=True)),
                ('caters_food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_food_caters')),
            ],
        ),
    ]
