# Generated by Django 5.0.6 on 2024-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_booking_restaurant_food_caters_food_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_food_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('food_image', models.ImageField(null=True, upload_to='')),
                ('uploaded_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
