# Generated by Django 5.0.6 on 2024-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_add_food_caters_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_caters_food',
            name='admin_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking_restaurant_food',
            name='admin_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
