# Generated by Django 5.0.6 on 2024-07-01 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_booking_caters_food_admin_uploaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_food_admin_to_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('food_image', models.ImageField(null=True, upload_to='')),
                ('uploaded_time', models.DateTimeField(null=True)),
                ('admin_food_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_food_admin')),
            ],
        ),
    ]
