# Generated by Django 5.0.6 on 2024-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_booking_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking_food',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_booking_food',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_booking_food',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
