# Generated by Django 5.0.6 on 2024-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_user_booking_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_booking_food',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
