# Generated by Django 5.0.6 on 2024-07-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_user_feedbacks_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_food_caters',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='add_food_restaurants',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
