# Generated by Django 5.0.6 on 2024-07-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_add_food_caters_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_food_caters',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='add_food_restaurants',
            name='rejected',
        ),
    ]
