# Generated by Django 5.0.6 on 2024-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_add_food_caters_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_food_caters',
            name='accepted',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='add_food_restaurants',
            name='accepted',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
